# Generated by Django 5.2.5 on 2025-08-18 13:51

import django.db.models.deletion
import repository.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('slug', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('resolution', 'SB Resolution'), ('ordinance', 'Ordinance'), ('appropriation', 'Appropriation Ordinance')], max_length=150)),
                ('title', models.TextField()),
                ('slug', models.TextField()),
                ('date_approved', models.DateField()),
                ('pdf_file', models.FileField(upload_to=repository.models.legal_measure_path)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('portrait', models.ImageField(blank=True, default='static/images/johndoe.png', null=True, upload_to='legislator/portrait')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('co_author', 'Co-Author'), ('sponsor', 'Sponsor')], max_length=50)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='repository.committee')),
                ('legal_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_measure', to='repository.legalmeasure')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='legal_measure',
            field=models.ManyToManyField(related_name='measures', through='repository.CommitteeMeasure', to='repository.legalmeasure'),
        ),
        migrations.CreateModel(
            name='LegislatorTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('councilor', 'Municipal Councilor'), ('vice_mayor', 'Municipal Vice Mayor'), ('abc_president', 'ABC President'), ('ip_representative', 'IP Representative'), ('sk_federation_president', 'SK Municipal Federation President')], max_length=150)),
                ('start_of_term', models.DateField()),
                ('end_of_term', models.DateField()),
                ('remarks', models.TextField()),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='repository.legislator')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairman', 'Chairman'), ('vice_chairman', 'Vice Chairman'), ('member', 'member')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='repository.committee')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_membership', to='repository.legislatorterms')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='legislator',
            field=models.ManyToManyField(related_name='legislators', through='repository.CommitteeMembership', to='repository.legislatorterms'),
        ),
        migrations.CreateModel(
            name='MeasureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('amended', 'Amended'), ('related', 'Related')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('legal_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_measure', to='repository.legalmeasure')),
                ('related_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_measure', to='repository.legalmeasure')),
            ],
        ),
        migrations.AddField(
            model_name='legalmeasure',
            name='related_measures',
            field=models.ManyToManyField(through='repository.MeasureRelation', through_fields=('legal_measure', 'related_measure'), to='repository.legalmeasure'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('co_author', 'Co-Author'), ('sponsor', 'Sponsor')], max_length=50)),
                ('legal_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='repository.legalmeasure')),
                ('legislator_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='repository.legislatorterms')),
            ],
        ),
        migrations.AddField(
            model_name='legalmeasure',
            name='legislator',
            field=models.ManyToManyField(related_name='measures', through='repository.Participation', to='repository.legislatorterms'),
        ),
    ]
