# Generated by Django 5.2.5 on 2025-08-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegislatorTerms',
            new_name='LegislatorTerm',
        ),
    ]
