# Generated by Django 5.2.5 on 2025-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_rename_legislatorterms_legislatorterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislatorterm',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
