# Generated by Django 5.2.5 on 2025-08-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_legislatorterm_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalmeasure',
            name='number',
            field=models.CharField(default='number', max_length=250),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='role',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Member', 'member')], max_length=100),
        ),
        migrations.AlterField(
            model_name='legislatorterm',
            name='position',
            field=models.CharField(choices=[('Councilor', 'Municipal Councilor'), ('Municipal Vice Mayor', 'Municipal Vice Mayor'), ('ABC President', 'ABC President'), ('IP Representative', 'IP Representative'), ('SK Municipal Federation President', 'SK Municipal Federation President')], max_length=150),
        ),
    ]
