# Generated by Django 5.2.5 on 2025-08-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_legalmeasure_number_alter_committeemembership_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislatorterm',
            options={'verbose_name': 'Legislator', 'verbose_name_plural': 'Legislators'},
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='legislator_term',
            new_name='legislator',
        ),
        migrations.AlterField(
            model_name='legalmeasure',
            name='related_measures',
            field=models.ManyToManyField(blank=True, null=True, through='repository.MeasureRelation', through_fields=('legal_measure', 'related_measure'), to='repository.legalmeasure'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('legislator', 'legal_measure', 'role'), name='unique_legislator_measure_role'),
        ),
    ]
