# Generated by Django 5.2.5 on 2025-08-23 05:42

import repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_alter_legislatorterm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='portrait',
            field=models.ImageField(blank=True, default='static/images/johndoe.png', null=True, upload_to=repository.models.profile_picture_path),
        ),
    ]
