# Generated by Django 5.2.5 on 2025-08-23 05:46

import repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_alter_legislator_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=repository.models.profile_picture_path),
        ),
    ]
