# Generated by Django 5.2.5 on 2025-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_alter_legislator_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalmeasure',
            name='type',
            field=models.CharField(choices=[('SB Resolution', 'SB Resolution'), ('Municipal Ordinance', 'Municipal Ordinance'), ('Appropriation Ordinance', 'Appropriation Ordinance')], max_length=150),
        ),
    ]
