# Generated by Django 5.2.5 on 2025-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_alter_legalmeasure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Co-Author', 'Co-Author'), ('Sponsor', 'Sponsor')], max_length=50),
        ),
    ]
