# Generated by Django 5.2.5 on 2025-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_alter_participation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemeasure',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Co-Author', 'Co-Author'), ('Sponsor', 'Sponsor')], max_length=50),
        ),
    ]
