# Generated by Django 5.2.5 on 2025-08-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_alter_committeemeasure_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalmeasure',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='legalmeasure',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='legalmeasure',
            name='number',
            field=models.CharField(default='number', max_length=150),
        ),
    ]
