# Generated by Django 5.2.5 on 2025-08-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_legalmeasure_numbers_legalmeasure_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalmeasure',
            name='numbers',
            field=models.IntegerField(),
        ),
    ]
