# Generated by Django 5.2.5 on 2025-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_alter_legalmeasure_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalmeasure',
            name='numbers',
        ),
        migrations.AlterField(
            model_name='legalmeasure',
            name='number',
            field=models.IntegerField(),
        ),
    ]
