# Generated by Django 5.2.5 on 2025-08-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_remove_legalmeasure_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalmeasure',
            name='suffix',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
