# Generated by Django 5.2.5 on 2025-08-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_legalmeasure_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalmeasure',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalmeasure',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
