# Generated by Django 5.2.5 on 2025-08-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_alter_legalmeasure_number_alter_legalmeasure_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalmeasure',
            old_name='number',
            new_name='sequence',
        ),
    ]
