# Generated by Django 5.2.5 on 2025-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_rename_number_legalmeasure_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalmeasure',
            options={'verbose_name': 'Legal Measure'},
        ),
        migrations.AlterModelOptions(
            name='legislatorterm',
            options={'verbose_name': 'Legislator Term', 'verbose_name_plural': 'Legislator Terms'},
        ),
        migrations.RenameField(
            model_name='measurerelation',
            old_name='legal_measure',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='measurerelation',
            old_name='related_measure',
            new_name='target',
        ),
        migrations.AlterField(
            model_name='legalmeasure',
            name='related_measures',
            field=models.ManyToManyField(blank=True, through='repository.MeasureRelation', through_fields=('source', 'target'), to='repository.legalmeasure'),
        ),
    ]
