# Generated by Django 5.2.5 on 2025-08-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_alter_legalmeasure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurerelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_source', to='repository.legalmeasure', verbose_name='Original Measure'),
        ),
        migrations.AlterField(
            model_name='measurerelation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_target', to='repository.legalmeasure', verbose_name='Related Measure'),
        ),
    ]
