# Generated by Django 5.2.5 on 2025-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_alter_measurerelation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
