# Generated by Django 5.2.5 on 2025-09-05 14:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_legislator_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='biography',
            field=django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='Content'),
        ),
    ]
