# Generated by Django 5.2.5 on 2025-09-16 13:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_alter_legislator_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='True', max_length=250, null=True)),
                ('address', models.CharField(blank='True', max_length=200, null=True)),
                ('municipality', models.CharField(blank='True', max_length=100, null=True)),
                ('province', models.CharField(blank='True', max_length=100, null=True)),
                ('short_mandate', django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='description')),
                ('mandate', django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='mandate')),
                ('publication_header', models.CharField(blank='True', max_length=200, null=True)),
                ('publication_description', django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='mandate')),
            ],
        ),
        migrations.AlterField(
            model_name='legislatorterm',
            name='position',
            field=models.CharField(choices=[('Municipal Councilor', 'Municipal Councilor'), ('Municipal Vice Mayor', 'Municipal Vice Mayor'), ('ABC President', 'ABC President'), ('IP Representative', 'IP Representative'), ('SK Municipal Federation President', 'SK Municipal Federation President')], max_length=150),
        ),
    ]
