# Generated by Django 5.2.5 on 2025-09-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_sbprofile_alter_legislatorterm_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbprofile',
            options={'verbose_name': 'Profile'},
        ),
    ]
