# Generated by Django 5.2.5 on 2025-09-16 14:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_alter_sbprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbprofile',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='publication description'),
        ),
        migrations.AddField(
            model_name='sbprofile',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='publication description'),
        ),
        migrations.AlterField(
            model_name='sbprofile',
            name='publication_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='publication description'),
        ),
        migrations.AlterField(
            model_name='sbprofile',
            name='short_mandate',
            field=django_ckeditor_5.fields.CKEditor5Field(blank='True', null=True, verbose_name='short mandate'),
        ),
    ]
